# Stage 1 - Base image to build npm packages
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Stage 2 - Production image to run the app
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app ./

EXPOSE 5173
CMD [ "npm", "run", "dev" ]
